version: "3.8"
services:
  vue-frontend:
    build: 
      context: .
      dockerfile: Dockerfile.local
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_APPLE_CLIENT_ID=${VITE_APPLE_CLIENT_ID}
        - VITE_APPLE_REDIRECT_URI=${VITE_APPLE_REDIRECT_URI}
    container_name: osp-frontend
    ports:
      - "8001:80" 
    env_file:
      - .env
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: osp-frontend-cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_FRONTEND_TUNNEL_TOKEN}
    depends_on:
      - vue-frontend
    restart: unless-stopped
